set_property SRC_FILE_INFO {cfile:{C:/Users/Samir Ahmed/OneDrive - University of South Florida/PHS/APUF_Files/APUF_Files/Lab-01-APUF/Lab-01-APUF.srcs/constrs_3/new/APUF_constr.xdc} rfile:../Lab-01-APUF.srcs/constrs_3/new/APUF_constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y26 [get_cells A/PCSPUF/bot7/muxOut]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y26 [get_cells A/PCSPUF/bot7/c6LUT]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y26 [get_cells A/PCSPUF/bot7/d6LUT]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot7/c6LUT]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot7/d6LUT]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7AMUX [get_cells A/PCSPUF/bot7/muxOut]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/*/abar_LUT]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/*/bbar_LUT]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/*/cbar_LUT]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/*/dbar_LUT]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/*7/c6LUT]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/*7/d6LUT]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7AMUX [get_cells A/PCSPUF/*7/muxOut]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/topEnableLUT]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y32 [get_cells A/topEnableLUT]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7AMUX [get_cells A/topEnableMUX]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y32 [get_cells A/topEnableMUX]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/botEnableLUT]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y30 [get_cells A/botEnableLUT]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7AMUX [get_cells A/botEnableMUX]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y30 [get_cells A/botEnableMUX]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/primaryEnableLUT]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y31 [get_cells A/primaryEnableLUT]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7AMUX [get_cells A/primaryEnableMUX]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y31 [get_cells A/primaryEnableMUX]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top0/abar_LUT]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top0/bbar_LUT]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top0/cbar_LUT]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top0/dbar_LUT]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y32 [get_cells A/PCSPUF/top0/*bar_LUT]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top0/c6LUT]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y32 [get_cells A/PCSPUF/top0/c6LUT]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top0/d6LUT]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y32 [get_cells A/PCSPUF/top0/d6LUT]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top0/muxOut]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y32 [get_cells A/PCSPUF/top0/muxOut]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot0/abar_LUT]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot0/bbar_LUT]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot0/cbar_LUT]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot0/dbar_LUT]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y30 [get_cells A/PCSPUF/bot0/*bar_LUT]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot0/c6LUT]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y30 [get_cells A/PCSPUF/bot0/c6LUT]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot0/d6LUT]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y30 [get_cells A/PCSPUF/bot0/d6LUT]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot0/muxOut]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y30 [get_cells A/PCSPUF/bot0/muxOut]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top1/abar_LUT]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top1/bbar_LUT]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top1/cbar_LUT]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top1/dbar_LUT]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y32 [get_cells A/PCSPUF/top1/*bar_LUT]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top1/c6LUT]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y32 [get_cells A/PCSPUF/top1/c6LUT]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top1/d6LUT]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y32 [get_cells A/PCSPUF/top1/d6LUT]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top1/muxOut]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y32 [get_cells A/PCSPUF/top1/muxOut]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot1/abar_LUT]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot1/bbar_LUT]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot1/cbar_LUT]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot1/dbar_LUT]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y30 [get_cells A/PCSPUF/bot1/*bar_LUT]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot1/c6LUT]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y30 [get_cells A/PCSPUF/bot1/c6LUT]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot1/d6LUT]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y30 [get_cells A/PCSPUF/bot1/d6LUT]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot1/muxOut]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y30 [get_cells A/PCSPUF/bot1/muxOut]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top2/abar_LUT]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top2/bbar_LUT]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top2/cbar_LUT]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top2/dbar_LUT]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y32 [get_cells A/PCSPUF/top2/*bar_LUT]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top2/c6LUT]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y32 [get_cells A/PCSPUF/top2/c6LUT]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top2/d6LUT]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y32 [get_cells A/PCSPUF/top2/d6LUT]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top2/muxOut]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y32 [get_cells A/PCSPUF/top2/muxOut]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot2/abar_LUT]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot2/bbar_LUT]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot2/cbar_LUT]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot2/dbar_LUT]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y30 [get_cells A/PCSPUF/bot2/*bar_LUT]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot2/c6LUT]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y30 [get_cells A/PCSPUF/bot2/c6LUT]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot2/d6LUT]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y30 [get_cells A/PCSPUF/bot2/d6LUT]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot2/muxOut]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y30 [get_cells A/PCSPUF/bot2/muxOut]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top3/abar_LUT]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top3/bbar_LUT]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top3/cbar_LUT]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top3/dbar_LUT]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X8Y32 [get_cells A/PCSPUF/top3/*bar_LUT]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top3/c6LUT]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y32 [get_cells A/PCSPUF/top3/c6LUT]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top3/d6LUT]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y32 [get_cells A/PCSPUF/top3/d6LUT]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top3/muxOut]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y32 [get_cells A/PCSPUF/top3/muxOut]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot3/abar_LUT]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot3/bbar_LUT]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot3/cbar_LUT]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot3/dbar_LUT]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X8Y30 [get_cells A/PCSPUF/bot3/*bar_LUT]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot3/c6LUT]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y30 [get_cells A/PCSPUF/bot3/c6LUT]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot3/d6LUT]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y30 [get_cells A/PCSPUF/bot3/d6LUT]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot3/muxOut]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y30 [get_cells A/PCSPUF/bot3/muxOut]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top4/abar_LUT]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top4/bbar_LUT]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top4/cbar_LUT]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top4/dbar_LUT]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X8Y28 [get_cells A/PCSPUF/top4/*bar_LUT]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top4/c6LUT]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y28 [get_cells A/PCSPUF/top4/c6LUT]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top4/d6LUT]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y28 [get_cells A/PCSPUF/top4/d6LUT]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top4/muxOut]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y28 [get_cells A/PCSPUF/top4/muxOut]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot4/abar_LUT]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot4/bbar_LUT]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot4/cbar_LUT]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot4/dbar_LUT]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X8Y26 [get_cells A/PCSPUF/bot4/*bar_LUT]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot4/c6LUT]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y26 [get_cells A/PCSPUF/bot4/c6LUT]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot4/d6LUT]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y26 [get_cells A/PCSPUF/bot4/d6LUT]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot4/muxOut]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y26 [get_cells A/PCSPUF/bot4/muxOut]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top5/abar_LUT]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top5/bbar_LUT]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top5/cbar_LUT]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top5/dbar_LUT]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y28 [get_cells A/PCSPUF/top5/*bar_LUT]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top5/c6LUT]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y28 [get_cells A/PCSPUF/top5/c6LUT]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top5/d6LUT]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y28 [get_cells A/PCSPUF/top5/d6LUT]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top5/muxOut]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y28 [get_cells A/PCSPUF/top5/muxOut]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot5/abar_LUT]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot5/bbar_LUT]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot5/cbar_LUT]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot5/dbar_LUT]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y26 [get_cells A/PCSPUF/bot5/*bar_LUT]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot5/c6LUT]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y26 [get_cells A/PCSPUF/bot5/c6LUT]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot5/d6LUT]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y26 [get_cells A/PCSPUF/bot5/d6LUT]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot5/muxOut]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y26 [get_cells A/PCSPUF/bot5/muxOut]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top6/abar_LUT]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top6/bbar_LUT]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top6/cbar_LUT]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top6/dbar_LUT]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y28 [get_cells A/PCSPUF/top6/*bar_LUT]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top6/c6LUT]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y28 [get_cells A/PCSPUF/top6/c6LUT]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top6/d6LUT]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y28 [get_cells A/PCSPUF/top6/d6LUT]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/top6/muxOut]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y28 [get_cells A/PCSPUF/top6/muxOut]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot6/abar_LUT]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot6/bbar_LUT]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot6/cbar_LUT]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot6/dbar_LUT]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y26 [get_cells A/PCSPUF/bot6/*bar_LUT]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot6/c6LUT]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y26 [get_cells A/PCSPUF/bot6/c6LUT]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot6/d6LUT]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y26 [get_cells A/PCSPUF/bot6/d6LUT]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7BMUX [get_cells A/PCSPUF/bot6/muxOut]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y26 [get_cells A/PCSPUF/bot6/muxOut]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top7/abar_LUT]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top7/bbar_LUT]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/top7/cbar_LUT]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/top7/dbar_LUT]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y28 [get_cells A/PCSPUF/top7/*bar_LUT]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/top7/c6LUT]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y28 [get_cells A/PCSPUF/top7/c6LUT]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/top7/d6LUT]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y28 [get_cells A/PCSPUF/top7/d6LUT]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F7AMUX [get_cells A/PCSPUF/top7/muxOut]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y28 [get_cells A/PCSPUF/top7/muxOut]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells A/PCSPUF/bot7/abar_LUT]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells A/PCSPUF/bot7/bbar_LUT]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells A/PCSPUF/bot7/cbar_LUT]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells A/PCSPUF/bot7/dbar_LUT]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y26 [get_cells A/PCSPUF/bot7/*bar_LUT]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells A/PCSPUF/DFF/Q_reg]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y27 [get_cells A/PCSPUF/DFF/Q_reg]
